#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

exec "$script_dir/pev" "$@" --livestream -1 --num-instances 4 --wbc_env_config.visualize --terrain-type flat
